import type { UserSettings, UserThemePalette } from '@/modules/User/types/user.types';

export const USER_THEME_PALETTES: readonly UserThemePalette[] = [
    {
        id: 'aurora-tide',
        name: 'Aurora Tide',
        tagline: 'Electric polar bloom drifting over midnight seas.',
        ui: {
            backgroundStart: '#08101d',
            backgroundMid: '#17385d',
            backgroundEnd: '#02050c',
            surface: 'rgba(7, 15, 30, 0.9)',
            surfaceBorder: 'rgba(126, 247, 192, 0.2)',
            accent: '#7ef7c0',
            accentSoft: 'rgba(126, 247, 192, 0.1)',
            text: '#f2fbff',
            textMuted: '#9cb8c9',
        },
        globe: {
            background: '#050915',
            globeColor: '#2f7df6',
            globeEmissive: '#1a5ee6',
            atmosphereColor: '#6ce4ff',
            atmosphereNightColor: '#0d2148',
            ambientLight: '#6b7aa8',
            sunLight: '#fff3d6',
        },
    },
    {
        id: 'solar-flare',
        name: 'Solar Flare',
        tagline: 'Copper light, hot horizons, and a planet at golden hour.',
        ui: {
            backgroundStart: '#1a0f0b',
            backgroundMid: '#5c2915',
            backgroundEnd: '#090304',
            surface: 'rgba(20, 11, 10, 0.9)',
            surfaceBorder: 'rgba(255, 184, 112, 0.2)',
            accent: '#ffb870',
            accentSoft: 'rgba(255, 184, 112, 0.1)',
            text: '#fff5ef',
            textMuted: '#cdb29f',
        },
        globe: {
            background: '#100709',
            globeColor: '#8f4724',
            globeEmissive: '#ff8e3d',
            atmosphereColor: '#ffc170',
            atmosphereNightColor: '#35140a',
            ambientLight: '#7f6856',
            sunLight: '#ffe1b4',
        },
    },
    {
        id: 'emerald-canopy',
        name: 'Emerald Canopy',
        tagline: 'Rainforest glow, jade oceans, and humid starlight.',
        ui: {
            backgroundStart: '#07130f',
            backgroundMid: '#16382a',
            backgroundEnd: '#020705',
            surface: 'rgba(6, 18, 15, 0.9)',
            surfaceBorder: 'rgba(110, 241, 183, 0.18)',
            accent: '#6ef1b7',
            accentSoft: 'rgba(110, 241, 183, 0.1)',
            text: '#f0fff7',
            textMuted: '#9dbfae',
        },
        globe: {
            background: '#05100c',
            globeColor: '#1f7156',
            globeEmissive: '#25c987',
            atmosphereColor: '#7ff4ca',
            atmosphereNightColor: '#0a281d',
            ambientLight: '#587766',
            sunLight: '#edfff4',
        },
    },
    {
        id: 'rose-nebula',
        name: 'Rose Nebula',
        tagline: 'Dusty crimson haze with soft champagne highlights.',
        ui: {
            backgroundStart: '#160d14',
            backgroundMid: '#412235',
            backgroundEnd: '#060307',
            surface: 'rgba(18, 10, 17, 0.9)',
            surfaceBorder: 'rgba(255, 165, 198, 0.18)',
            accent: '#f3a3c2',
            accentSoft: 'rgba(243, 163, 194, 0.1)',
            text: '#fff5f8',
            textMuted: '#c7aab8',
        },
        globe: {
            background: '#10070f',
            globeColor: '#723251',
            globeEmissive: '#d36495',
            atmosphereColor: '#ffb9dd',
            atmosphereNightColor: '#2a1121',
            ambientLight: '#786373',
            sunLight: '#ffe5ed',
        },
    },
    {
        id: 'nocturne-ice',
        name: 'Nocturne Ice',
        tagline: 'Glacial blue fire with sharp moonlit contrast.',
        ui: {
            backgroundStart: '#04111b',
            backgroundMid: '#12395d',
            backgroundEnd: '#010408',
            surface: 'rgba(4, 14, 26, 0.9)',
            surfaceBorder: 'rgba(115, 211, 255, 0.2)',
            accent: '#73d3ff',
            accentSoft: 'rgba(115, 211, 255, 0.1)',
            text: '#f1f8ff',
            textMuted: '#9bb8cb',
        },
        globe: {
            background: '#03101c',
            globeColor: '#1c5e94',
            globeEmissive: '#4ab3ff',
            atmosphereColor: '#a5e7ff',
            atmosphereNightColor: '#0a203d',
            ambientLight: '#4d6e8c',
            sunLight: '#e7fbff',
        },
    },
];

export const DEFAULT_USER_SETTINGS: UserSettings = {
    themeId: USER_THEME_PALETTES[0]!.id,
    brightness: 1,
    nickname: '',
    yearOfBirth: '',
    homeCountryCode: '',
    homeCountryName: '',
    homeCityId: '',
    homeCityName: '',
    currentLocationCountryCode: '',
    currentLocationCountryName: '',
    currentLocationCityId: '',
    currentLocationCityName: '',
    currentLocationLatitude: null,
    currentLocationLongitude: null,
};

export function resolveUserThemePalette(themeId: string): UserThemePalette {
    return USER_THEME_PALETTES.find((themePalette) => themePalette.id === themeId) ?? USER_THEME_PALETTES[0]!;
}
