import type { UserSettings, UserThemePalette } from '@/modules/User/types/user.types';

export const USER_THEME_PALETTES: readonly UserThemePalette[] = [
    {
        id: 'aurora-tide',
        name: 'Aurora Tide',
        tagline: 'Electric polar bloom drifting over midnight seas.',
        ui: {
            backgroundStart: '#091122',
            backgroundMid: '#13294d',
            backgroundEnd: '#02040b',
            surface: 'rgba(8, 18, 36, 0.82)',
            surfaceBorder: 'rgba(126, 247, 192, 0.22)',
            accent: '#7ef7c0',
            accentSoft: 'rgba(126, 247, 192, 0.16)',
            text: '#eefbff',
            textMuted: '#95b8ca',
        },
        globe: {
            background: '#050915',
            globeColor: '#2f7df6',
            globeEmissive: '#1a5ee6',
            atmosphereColor: '#6ce4ff',
            atmosphereNightColor: '#0d2148',
            ambientLight: '#6b7aa8',
            sunLight: '#fff3d6',
        },
    },
    {
        id: 'solar-flare',
        name: 'Solar Flare',
        tagline: 'Copper light, hot horizons, and a planet at golden hour.',
        ui: {
            backgroundStart: '#24110a',
            backgroundMid: '#52291c',
            backgroundEnd: '#080305',
            surface: 'rgba(34, 14, 11, 0.84)',
            surfaceBorder: 'rgba(255, 176, 108, 0.22)',
            accent: '#ffb06c',
            accentSoft: 'rgba(255, 176, 108, 0.16)',
            text: '#fff2ea',
            textMuted: '#d6ad97',
        },
        globe: {
            background: '#12070a',
            globeColor: '#9c4a18',
            globeEmissive: '#ff8c32',
            atmosphereColor: '#ffb25f',
            atmosphereNightColor: '#351108',
            ambientLight: '#94614a',
            sunLight: '#ffd5a0',
        },
    },
    {
        id: 'emerald-canopy',
        name: 'Emerald Canopy',
        tagline: 'Rainforest glow, jade oceans, and humid starlight.',
        ui: {
            backgroundStart: '#08170f',
            backgroundMid: '#183d2b',
            backgroundEnd: '#020908',
            surface: 'rgba(6, 24, 18, 0.84)',
            surfaceBorder: 'rgba(118, 255, 196, 0.22)',
            accent: '#76ffc4',
            accentSoft: 'rgba(118, 255, 196, 0.16)',
            text: '#eefef6',
            textMuted: '#95c8b1',
        },
        globe: {
            background: '#04110b',
            globeColor: '#1f8a64',
            globeEmissive: '#1dcb88',
            atmosphereColor: '#7fffd1',
            atmosphereNightColor: '#0a2a1e',
            ambientLight: '#56836d',
            sunLight: '#e8fff0',
        },
    },
    {
        id: 'rose-nebula',
        name: 'Rose Nebula',
        tagline: 'Dusty crimson haze with soft champagne highlights.',
        ui: {
            backgroundStart: '#1e0c17',
            backgroundMid: '#4b1f39',
            backgroundEnd: '#060208',
            surface: 'rgba(31, 10, 23, 0.84)',
            surfaceBorder: 'rgba(255, 154, 190, 0.22)',
            accent: '#ff9abe',
            accentSoft: 'rgba(255, 154, 190, 0.16)',
            text: '#fff1f6',
            textMuted: '#d2a4b8',
        },
        globe: {
            background: '#120713',
            globeColor: '#81305a',
            globeEmissive: '#d6568c',
            atmosphereColor: '#ffadd7',
            atmosphereNightColor: '#2f1022',
            ambientLight: '#8a6280',
            sunLight: '#ffe0ea',
        },
    },
    {
        id: 'nocturne-ice',
        name: 'Nocturne Ice',
        tagline: 'Glacial blue fire with sharp moonlit contrast.',
        ui: {
            backgroundStart: '#041421',
            backgroundMid: '#0d3151',
            backgroundEnd: '#010408',
            surface: 'rgba(4, 16, 28, 0.84)',
            surfaceBorder: 'rgba(115, 211, 255, 0.22)',
            accent: '#73d3ff',
            accentSoft: 'rgba(115, 211, 255, 0.16)',
            text: '#eff8ff',
            textMuted: '#93b7cf',
        },
        globe: {
            background: '#03101c',
            globeColor: '#1c5e94',
            globeEmissive: '#4ab3ff',
            atmosphereColor: '#a5e7ff',
            atmosphereNightColor: '#0a203d',
            ambientLight: '#4d6e8c',
            sunLight: '#e7fbff',
        },
    },
];

export const DEFAULT_USER_SETTINGS: UserSettings = {
    themeId: USER_THEME_PALETTES[0]!.id,
    brightness: 1,
    nickname: '',
    yearOfBirth: '',
    homeCountryCode: '',
    homeCountryName: '',
};

export function resolveUserThemePalette(themeId: string): UserThemePalette {
    return USER_THEME_PALETTES.find((themePalette) => themePalette.id === themeId) ?? USER_THEME_PALETTES[0]!;
}
