import type { UserSettings, UserThemePalette } from '@/modules/User/types/user.types';

export const USER_THEME_PALETTES: readonly UserThemePalette[] = [
    {
        id: 'aurora-tide',
        name: 'Aurora Tide',
        tagline: 'Electric polar bloom drifting over midnight seas.',
        ui: {
            backgroundStart: '#08101d',
            backgroundMid: '#17385d',
            backgroundEnd: '#02050c',
            surface: 'rgba(7, 15, 30, 0.9)',
            surfaceBorder: 'rgba(126, 247, 192, 0.2)',
            accent: '#7ef7c0',
            accentSoft: 'rgba(126, 247, 192, 0.1)',
            text: '#f2fbff',
            textMuted: '#9cb8c9',
        },
        globe: {
            background: '#050915',
            globeColor: '#1a68e0',
            globeEmissive: '#0f48c8',
            atmosphereColor: '#28c8f0',
            atmosphereNightColor: '#081840',
            ambientLight: '#3a5090',
            sunLight: '#ffe090',
        },
    },
    {
        id: 'solar-flare',
        name: 'Solar Flare',
        tagline: 'Copper light, hot horizons, and a planet at golden hour.',
        ui: {
            backgroundStart: '#1a0f0b',
            backgroundMid: '#5c2915',
            backgroundEnd: '#090304',
            surface: 'rgba(20, 11, 10, 0.9)',
            surfaceBorder: 'rgba(255, 184, 112, 0.2)',
            accent: '#ffb870',
            accentSoft: 'rgba(255, 184, 112, 0.1)',
            text: '#fff5ef',
            textMuted: '#cdb29f',
        },
        globe: {
            background: '#100709',
            globeColor: '#7a3010',
            globeEmissive: '#d05820',
            atmosphereColor: '#d06818',
            atmosphereNightColor: '#250a04',
            ambientLight: '#5e4025',
            sunLight: '#e09030',
        },
    },
    {
        id: 'emerald-canopy',
        name: 'Emerald Canopy',
        tagline: 'Rainforest glow, jade oceans, and humid starlight.',
        ui: {
            backgroundStart: '#07130f',
            backgroundMid: '#16382a',
            backgroundEnd: '#020705',
            surface: 'rgba(6, 18, 15, 0.9)',
            surfaceBorder: 'rgba(110, 241, 183, 0.18)',
            accent: '#6ef1b7',
            accentSoft: 'rgba(110, 241, 183, 0.1)',
            text: '#f0fff7',
            textMuted: '#9dbfae',
        },
        globe: {
            background: '#05100c',
            globeColor: '#135e40',
            globeEmissive: '#158050',
            atmosphereColor: '#28b870',
            atmosphereNightColor: '#061c12',
            ambientLight: '#2e5840',
            sunLight: '#70d898',
        },
    },
    {
        id: 'rose-nebula',
        name: 'Rose Nebula',
        tagline: 'Dusty crimson haze with soft champagne highlights.',
        ui: {
            backgroundStart: '#160d14',
            backgroundMid: '#412235',
            backgroundEnd: '#060307',
            surface: 'rgba(18, 10, 17, 0.9)',
            surfaceBorder: 'rgba(255, 165, 198, 0.18)',
            accent: '#f3a3c2',
            accentSoft: 'rgba(243, 163, 194, 0.1)',
            text: '#fff5f8',
            textMuted: '#c7aab8',
        },
        globe: {
            background: '#10070f',
            globeColor: '#5a1838',
            globeEmissive: '#a02860',
            atmosphereColor: '#c04080',
            atmosphereNightColor: '#1a0814',
            ambientLight: '#582848',
            sunLight: '#e888a0',
        },
    },
    {
        id: 'nocturne-ice',
        name: 'Nocturne Ice',
        tagline: 'Glacial blue fire with sharp moonlit contrast.',
        ui: {
            backgroundStart: '#04111b',
            backgroundMid: '#12395d',
            backgroundEnd: '#010408',
            surface: 'rgba(4, 14, 26, 0.9)',
            surfaceBorder: 'rgba(115, 211, 255, 0.2)',
            accent: '#73d3ff',
            accentSoft: 'rgba(115, 211, 255, 0.1)',
            text: '#f1f8ff',
            textMuted: '#9bb8cb',
        },
        globe: {
            background: '#03101c',
            globeColor: '#0c4880',
            globeEmissive: '#2090e0',
            atmosphereColor: '#48c8f0',
            atmosphereNightColor: '#051530',
            ambientLight: '#285070',
            sunLight: '#a0e8ff',
        },
    },
];

export const DEFAULT_USER_SETTINGS: UserSettings = {
    themeId: USER_THEME_PALETTES[0]!.id,
    brightness: 1,
    nickname: '',
    yearOfBirth: '',
    homeCountryCode: '',
    homeCountryName: '',
    homeCityId: '',
    homeCityName: '',
    currentLocationCountryCode: '',
    currentLocationCountryName: '',
    currentLocationCityId: '',
    currentLocationCityName: '',
    currentLocationLatitude: null,
    currentLocationLongitude: null,
    achievementState: {
        unlockedAchievementIds: [],
        lastUnlockedAt: null,
    },
};

export function resolveUserThemePalette(themeId: string): UserThemePalette {
    return USER_THEME_PALETTES.find((themePalette) => themePalette.id === themeId) ?? USER_THEME_PALETTES[0]!;
}
